import type { Metadata } from "next";
import "@/styles/globals.css";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Make Tiny Gains",
  description: "Generated by Omee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gradient-to-br from-blue-100 via-purple-100 to-pink-100 text-gray-900">
        <header className="w-full shadow bg-gradient-to-r from-blue-600 via-purple-500 to-pink-500">
          <NavBar />
        </header>
        <main className="p-4 max-w-6xl mx-auto"> {children}</main>
      </body>
    </html>
  );
}
